name: wallpaper_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.5.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  paginate_firestore: ^1.0.3+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  intl: ^0.17.0
  external_path:
    git:
      url: https://github.com/aakashkondhalkar/external_path

  flutter_downloader: ^1.4.4
  firebase_core :
  cloud_firestore: ^3.1.12
  font_awesome_flutter: ^8.5.0
  dots_indicator: ^1.1.0
  carousel_slider: ^4.0.0
  sliding_up_panel: ^0.3.6
  flutter_staggered_grid_view: ^0.3.0
  provider: ^6.0.2
  shared_preferences: ^0.5.4+3
  google_sign_in: ^4.4.6
  firebase_auth: ^3.3.14
  connectivity: ^0.4.5+3
  cached_network_image: ^2.2.0+1
  launch_review: ^3.0.1
  awesome_dialog: ^2.2.0
  onesignal_flutter: ^3.3.0
  shimmer: ^1.1.1
  clipboard: ^0.1.3
  #music_player: ^0.1.5
  # firebase_admob: ^0.9.3+2
  package_info: ^0.4.1
  #firebase_remote_config: ^2.0.4
  line_awesome_icons: ^1.0.4+2
  flutter_bloc: ^8.0.1
  eva_icons_flutter: ^2.0.0
  url_launcher: ^6.0.20
  fluttertoast: ^8.0.9
  #fzwallpaper: ^1.0.2
  wallpaper: ^1.1.0
  flutter_custom_tabs: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9


  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon.png"


flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    
    - assets/images/icon.png
    - assets/images/splash.png
    - assets/images/anish.jpg
 
  fonts:



    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/KulimPark-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/KulimPark-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/KulimPark-Bold.ttf
          weight: 800
